### PR TITLE
accept symbol as mock/stub name

### PR DESCRIPTION
**Pull request by nitishr**
Looking at #353 and #347 , I thought instead of deprecating / preventing calling Mocha::API#mock or #stub with single symbol, we could treat the first symbol as the test double name, i.e. accept strings as well as symbols for test double names.

There's a bit of duplication I'd like to remove, but only if the basic idea is acceptable.

### CODE REVIEW

**Comment by floehopper** [comment]
@nitishr I think this is a good idea. Thanks for suggesting it!

* I think I'd prefer the extra tests to be written out explicitly rather than using loops inside existing tests, even if that results in some duplication - that way the test name can be more specific.

* Although it doesn't look like it causes any problems, I think I'd prefer it if the `@name` instance variable in `Mocha::Name` was always converted to be a `String`.

I'll leave you in peace to remove the duplication you mentioned. Let me know when it's ready for a full review.

**Comment by nitishr** [comment]
@floehopper ready for a full review (as are my other 2 PRs).

**Comment by floehopper** [comment]
> ready for a full review (as are my other 2 PRs).

I've reviewed one of your other PRs, but unfortunately I've run out of time now. I'll try to review the remaining one as soon as I can. Thanks again for all your work! 😄

**Comment by nitishr** [comment]
Done! Can you please re-review?

**Pull request merged**
