### PR TITLE
Failing test for #272 in Ruby v2.3

### PR DESCRIPTION
**Pull request by floehopper**
This is the simplest "failing" (i.e. hanging) test which I've been able to come up with so far to demonstrate the problem in #272.

### CODE REVIEW

**Comment by floehopper** [comment]
[This build failure](https://travis-ci.org/freerange/mocha/builds/166813233) demonstrates the problem is only happening in Ruby v2.3.

**Comment by chrisroos** [comment]
I've just pushed a change that fixes this failing test when using Ruby 2.3.

Let's see what Travis thinks about it.

**Comment by floehopper** [comment]
Looks like it just [passed in Ruby v2.3](https://travis-ci.org/freerange/mocha/jobs/167674261). Good work!

**Comment by chrisroos** [comment]
This seems to pass all tests, @floehopper. Do you think we can merge it and deploy a 1.2.1 version?

**Comment by floehopper** [comment]
@chrisroos: Sounds like a good idea to me.

**Comment by floehopper** [comment]
I'm going to get this merged and released.

**Comment by floehopper** [comment]
I merged this manually by squashing the two commits together in 6f1c8b9b6aa4253c8a990befcb89648f09512242. I hope that's OK.

I also added a known issue to the README in 25ffe21fc8f2b00e82327e788045fee79f5beb3e to explain the problem.

I've just released [Mocha v1.2.1](https://rubygems.org/gems/mocha/versions/1.2.1) which includes this fix.

**Pull request closed without merging**
