### PR TITLE
Allow generation of return values by block with invocation arguments

### PR DESCRIPTION
**Pull request by mattbornski**

### CODE REVIEW

**Comment by mattbornski** [comment]
@floehopper for your consideration

**Comment by kpatrick** [comment]
I want this too.

**Comment by chrisroos** [comment]
Hi @mattbornski and @kpatrick. Apologies it's taken such a long time to respond to this PR!

Can you help me understand the use case for this functionality? I haven't given it any real thought (and may well be misunderstanding the purpose of this change) but it seems slightly odd that I'd want to define some behaviour in a stubbed method.

**Comment by mattbornski** [comment]
@chrisroos I'm looking to see if I can find the specific case where I needed this any longer, but off the top of my head I believe one of the major reasons is for meta-programming tests.  For instance a function wherein the response includes the input somehow; if this gets called 12 times in a suite of tests I might prefer to set the expectation once with a block instead of each time with a static value.

**Comment by kpatrick** [comment]
I've switched to a non-ruby project recently, so this doesn't impact me at this time.

**Comment by chrisroos** [comment]
Thanks for the responses, @kpatrick and @mattbornski.

@mattbornski: Did you have any luck finding the specific case where you needed this behaviour? I'd really like to understand more about the problem this is trying to solve and seeing some real world code might help me do that.

**Comment by mattbornski** [comment]
The code in question is in a private repo, but imagine you have some static data (`foo.name`, `foo.features`) and some dynamically generated data (`foo.uuid`).  In your test you can of course lock down a lot of data, but you might not want/be able to effectively lock down some of the dynamically generated data (perhaps it comes from a DB in an integration test and it's simply not worth the effort and/or so invasive as to undermine the entire value of the test to force it to be static).

Now imagine you have a function in which the response is dynamic based on the input.  Because the function calls external services or is not core to the test, you don't want to actually invoke it in tests but just simulate the response.  One of the more effective ways to stub this function is to use Mocha to generate a return value based on the input value.

```def transmogrify(obj)
  unless obj.features.include?(:can_transmogrify)
    return TransmogrificationResult(:error, "object #{obj.uuid} does not support transmogrification: features are #{obj.features}")
  end
  return TransmogrificationResult(:success, new CoreObject(UUID.new(), {features: features + ['transmogrified'], root_object: obj.uuid})
end
```

I definitely understand that the example is a little simplistic but the use case of wanting to mock something dynamically based on the input is very real.

**Comment by chrisroos** [comment]
Thanks for following up with the example, @mattbornski. Unfortunately, I'm still struggling to get my head around when I'd use this.

Using your example code, I could imagine having tests like:

```ruby
def test_transmogrify_when_object_can_transmogrify
  transmogrifier = Transmogrifier.new
  object = mock('foo', 
    features: [:can_transmogrify],
    uuid: 'object-uuid'
  )
  result = transmogrifier.transmogrify(object)
  # assert success of transmogrification
end

def test_transmogrify_when_object_cannot_transmogrify
  transmogrifier = Transmogrifier.new
  object = mock('foo', 
    features: [:cannot_transmogrify],
    uuid: 'object-uuid'
  )
  result = transmogrifier.transmogrify(object)
  # assert failure of transmogrification
end
```

Can you illustrate how you'd use the functionality added in this PR to write similar tests? Maybe that'll help me understand what I'm currently missing.

**Comment by mattbornski** [comment]
Perhaps in a bigger test, such as an integration test, where the complexity
is harder to factor out?

In any case I'm using the branch of the PR without issues so if you
fundamentally don't see the need, my problems at least are already handled.

**Comment by chrisroos** [comment]
Hi @mattbornski. I appreciate the effort you've put into this PR and in trying to help me understand the problem it's solving. Unfortunately, I'm still unable to see when this would be useful. Given that you're currently using your own branch and I can't yet justify merging this to master I'm going to close this PR. I'm certainly still happy to be persuaded that this is useful so feel free to reopen it if you want to the continue the discussion.

**Comment by floehopper** [comment]
A relevant discussion continues in #224.

**Pull request closed without merging**
